name: Semgrep
on:
  pull_request: {}
  push:
    branches:
    - '**'
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - name: Checkout all branches/tags
        uses: actions/checkout@v6
        with: 
          fetch-depth: 0

      - name: Full scan on default branch, handle PRs
        if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || github.event_name == 'pull_request'
        run: semgrep ci

      - name: Diff scan on non-default branch (push)
        if: github.ref != 'refs/heads/main' && github.event_name == 'push'
        run: |
          export SEMGREP_BASELINE_REF="origin/main"
          semgrep ci
